sonar.projectKey=Questionxble_2dgameproject
sonar.organization=questionxble
sonar.host.url=https://sonarcloud.io
sonar.projectName=2dgameproject
sonar.sourceEncoding=UTF-8

sonar.sources=Assets/Scripts
sonar.tests=Assets/Tests
sonar.test.inclusions=Assets/Tests/**/*.cs

sonar.exclusions=Assets/**/Editor/**,Assets/**/Plugins/**,Assets/Textures/**,CodeCoverage/**,Documentation/**,Library/**,Logs/**,Temp/**,UserSettings/**,**/*.meta,**/*.asset,**/*.prefab,**/*.unity,**/*.mat,**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.svg,**/*.pdf,**/*.htm,**/*.html
sonar.cpd.exclusions=Assets/Tests/**/*.cs
sonar.cs.opencover.reportsPaths=CodeCoverage/**/*TestCoverageResults_*.xml
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300sonar.projectKey=Questionxble_2dgameproject
sonar.organization=questionxble
sonar.host.url=https://sonarcloud.io
sonar.projectName=2dgameproject
sonar.sourceEncoding=UTF-8

sonar.sources=Assets/Scripts
sonar.tests=Assets/Tests
sonar.test.inclusions=Assets/Tests/**/*.cs

sonar.exclusions=Assets/**/Editor/**,Assets/**/Plugins/**,Assets/Textures/**,CodeCoverage/**,Documentation/**,Library/**,Logs/**,Temp/**,UserSettings/**,**/*.meta,**/*.asset,**/*.prefab,**/*.unity,**/*.mat,**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.svg,**/*.pdf,**/*.htm,**/*.html
sonar.cpd.exclusions=Assets/Tests/**/*.cs
sonar.cs.opencover.reportsPaths=CodeCoverage/**/*TestCoverageResults_*.xml
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300